# Generated by Django 3.2 on 2021-04-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course_usergrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='the_user',
            name='coursesCompleted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course'),
        ),
    ]
