# Generated by Django 3.2 on 2021-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_the_user_coursescompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='the_user',
            name='coursesCompleted',
        ),
        migrations.AddField(
            model_name='the_user',
            name='coursesCompleted',
            field=models.ManyToManyField(null=True, related_name='student', to='base.Course'),
        ),
    ]
