# Generated by Django 3.1.4 on 2021-04-29 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210429_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrade',
            name='numGrade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
