# Generated by Django 3.1.4 on 2021-04-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210427_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='the_user',
            name='coursesCompleted',
            field=models.ManyToManyField(related_name='student', to='base.Course'),
        ),
    ]
