# Generated by Django 3.1.4 on 2021-04-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210427_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='endDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='startDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
