# Generated by Django 3.1.4 on 2021-04-27 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210427_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='the_user',
            name='coursesCompleted',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
